# Generated by Django 3.2.2 on 2023-04-10 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_event_organizer_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='gurukulam',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
