# Generated by Django 3.2.2 on 2023-07-10 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_location_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
    ]
