# Generated by Django 3.2.2 on 2023-07-12 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20230710_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='webtour',
            field=models.BooleanField(default=False),
        ),
    ]
