# Generated by Django 3.2.2 on 2023-07-13 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_user_webtour'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_subscription',
            field=models.BooleanField(default=False),
        ),
    ]
