# Generated by Django 3.2.2 on 2024-06-05 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20230906_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='account.post'),
        ),
    ]
