# Generated by Django 3.2.2 on 2024-06-06 18:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_post_comment_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Music_Lover',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField(blank=True, help_text='Date of Birth', null=True)),
                ('gender', models.CharField(choices=[('', 'Choose Gender'), ('M', 'Male'), ('F', 'Female'), ('T', 'Transgender'), ('N', 'None')], max_length=1, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='music_lover', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
