# Generated by Django 3.2.2 on 2023-04-10 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_event_event_video'),
    ]

    operations = [
       
    ]
