# Generated by Django 3.2.2 on 2023-06-26 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_location_name'),
        ('event', '0003_event_photos'),
    ]

    operations = [
       
   
        migrations.AlterField(
            model_name='interest',
            name='musician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='minterest', to='account.musician'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='musician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='minvitation', to='account.musician'),
        ),
    
    ]
