# Generated by Django 3.2.2 on 2023-07-13 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_auto_20230713_1108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='book_ticket_link_1',
            new_name='ticket_booking_link_1',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='book_ticket_link_2',
            new_name='ticket_booking_link_2',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='book_ticket_place',
            new_name='ticket_booking_place',
        )
  
    ]
