# Generated by Django 5.0.6 on 2024-07-04 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_remove_event_event_video_event_likes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='event',
            name='user_likes',
        ),
    ]
