# Generated by Django 5.0.6 on 2024-07-04 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_event_event_video'),
    ]

    operations = [
       
    ]
