# Generated by Django 5.0.6 on 2024-07-04 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0012_event_likes_event_user_likes'),
    ]

    operations = [
        
        
    ]
