# Generated by Django 5.1.2 on 2024-11-18 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_remove_event_event_video'),
        ('event', '0017_remove_event_bookmarks_bookmark'),
    ]

    operations = [
    ]
