# Generated by Django 3.2.2 on 2023-04-04 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('event_details', models.TextField()),
                ('from_date', models.DateTimeField(null=True)),
                ('to_date', models.DateTimeField(null=True)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('poster_image', models.ImageField(blank=True, null=True, upload_to='event_poster')),
                ('registration_close_date', models.DateField(null=True)),
                ('venue', models.CharField(blank=True, max_length=300, null=True)),
                ('self_reference', models.BooleanField(default=False)),
                ('highlight', models.TextField(null=True)),
                ('auto_accept', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Event_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Event_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('', 'Choose Status'), ('A', 'Accept'), ('R', 'Reject'), ('S', 'Sent')], max_length=1, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='event.event')),
                ('musician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.musician')),
                ('troupe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.troupe')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('', 'Choose Status'), ('A', 'Accept'), ('R', 'Reject'), ('S', 'Sent')], max_length=1, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='event.event')),
                ('gurukulam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.gurukulam')),
                ('musician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.musician')),
                ('troupe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.troupe')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Subscription_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('price', models.FloatField()),
                ('days', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_date', models.DateField(auto_now_add=True)),
                ('active', models.BooleanField(default=False)),
                ('event_organizer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.event_organizer')),
                ('gurukulam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.gurukulam')),
                ('musician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.musician')),
                ('subscription_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.subscription_type')),
                ('troupe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.troupe')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('sent_on', models.DateTimeField(auto_now_add=True)),
                ('unread', models.BooleanField(default=True)),
                ('interest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.interest')),
                ('invitation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.invitation')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event_Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event')),
                ('skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.skill')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='event_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event_category'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_organizer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.event_organizer'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event_type'),
        ),
        migrations.AddField(
            model_name='event',
            name='gurukulam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.gurukulam'),
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.location'),
        ),
    ]
